[package]
name = "pwr"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# polywrap_msgpack = "0.1.1"
